### ISSUE TITLE
I love dogs

### ISSUE THREAD

**Issue by s-a-ng** [shidemuri/scripts#1]
🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭 🐕 🐶 🌭

**Comment by shidemuri** [comment]
fuck off
